/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bUgO2cX1hfV
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";

export function Main() {
  return (
    <div className='flex flex-col min-h-screen'>
      <header className='bg-muted py-4 px-6 shadow-md'>
        <div className='container mx-auto flex items-center justify-between'>
          <div className='flex items-center'>
            <img
              src='/placeholder.svg'
              alt='Closer App Logo'
              className='mr-2'
              width='40'
              height='40'
              style={{ aspectRatio: "40/40", objectFit: "cover" }}
            />
            <h1 className='text-2xl font-bold'>Closer for macOS</h1>
          </div>
          <nav>
            <ul className='flex space-x-4'>
              <li>
                <Link
                  href='#'
                  className='text-foreground hover:text-accent'
                  prefetch={false}>
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href='#'
                  className='text-foreground hover:text-accent'
                  prefetch={false}>
                  Features
                </Link>
              </li>
              <li>
                <Link
                  href='#'
                  className='text-foreground hover:text-accent'
                  prefetch={false}>
                  Pricing
                </Link>
              </li>
              <li>
                <Link
                  href='#'
                  className='text-foreground hover:text-accent'
                  prefetch={false}>
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      <main className='flex-1'>
        <section className='w-full py-12 flex flex-col items-center justify-center text-center'>
          <div className='container px-4 md:px-6'>
            <div className='flex flex-col my-24 items-center justify-center min-h-96 bg-black text-white'>
              <div className='mb-8'>
                <img
                  src='/placeholder.svg'
                  alt='Closer Logo'
                  className='w-[300px] h-[300px]'
                  width='300'
                  height='300'
                  style={{ aspectRatio: "300/300", objectFit: "cover" }}
                />
              </div>
              <h1 className='text-4xl font-bold mb-4'>Closer for macOS</h1>
              <p className='text-lg mb-8 text-center max-w-xl'>
                Enhance macOS's default quit app functionality with Closer.
                Streamline your workflow and manage your applications more
                efficiently.
              </p>
            </div>
            <div className='flex flex-col gap-2 min-[400px]:flex-row justify-center mt-4'>
              <Link
                href='#'
                className='inline-flex h-10 items-center justify-center rounded-md bg-accent px-8 text-sm font-medium text-accent-foreground shadow transition-colors hover:bg-accent/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50'
                prefetch={false}>
                Download Now
              </Link>
              <Link
                href='#'
                className='inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50'
                prefetch={false}>
                Learn More
              </Link>
            </div>
          </div>
        </section>
        <section className='w-full py-12 md:py-24 lg:py-32 bg-muted'>
          <div className='container px-4 md:px-6'>
            <div className='grid gap-6 lg:grid-cols-2 lg:gap-12 items-center'>
              <div className='flex flex-col justify-center space-y-4 animate-fade'>
                <div className='space-y-2'>
                  <h2 className='text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none'>
                    Powerful Automation
                  </h2>
                  <p className='max-w-[600px] text-muted-foreground md:text-xl'>
                    Closer's automation features help you streamline your
                    workflow and boost your productivity.
                  </p>
                </div>
                <ul className='grid gap-2 py-4'>
                  <li>
                    <CheckIcon className='mr-2 inline-block h-4 w-4 text-accent' />
                    Automate repetitive tasks with custom scripts.
                  </li>
                  <li>
                    <CheckIcon className='mr-2 inline-block h-4 w-4 text-accent' />
                    Schedule app launches and closures for optimal workflow.
                  </li>
                  <li>
                    <CheckIcon className='mr-2 inline-block h-4 w-4 text-accent' />
                    Integrate with your favorite productivity tools.
                  </li>
                </ul>
              </div>
              <img
                src='/placeholder.svg'
                width='550'
                height='550'
                alt='Feature'
                className='mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-first lg:aspect-square animate-fade'
              />
            </div>
          </div>
        </section>
        <section className='w-full py-12 md:py-24 lg:py-32'>
          <div className='container px-4 md:px-6'>
            <div className='grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]'>
              <div className='flex flex-col justify-center space-y-4'>
                <div className='space-y-2'>
                  <h2 className='text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none'>
                    Intelligent Monitoring
                  </h2>
                  <p className='max-w-[600px] text-muted-foreground md:text-xl'>
                    Closer's monitoring features help you stay on top of your
                    app usage and system performance.
                  </p>
                </div>
                <ul className='grid gap-2 py-4'>
                  <li>
                    <CheckIcon className='mr-2 inline-block h-4 w-4 text-accent' />
                    Track app usage and system resource consumption.
                  </li>
                  <li>
                    <CheckIcon className='mr-2 inline-block h-4 w-4 text-accent' />
                    Receive alerts for critical system events.
                  </li>
                  <li>
                    <CheckIcon className='mr-2 inline-block h-4 w-4 text-accent' />
                    Optimize your workflow with data-driven insights.
                  </li>
                </ul>
                <div className='flex flex-col gap-2 min-[400px]:flex-row'>
                  <Link
                    href='#'
                    className='inline-flex h-10 items-center justify-center rounded-md bg-accent px-8 text-sm font-medium text-accent-foreground shadow transition-colors hover:bg-accent/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50'
                    prefetch={false}>
                    Download Now
                  </Link>
                  <Link
                    href='#'
                    className='inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50'
                    prefetch={false}>
                    Learn More
                  </Link>
                </div>
              </div>
              <img
                src='/placeholder.svg'
                width='550'
                height='550'
                alt='Feature'
                className='mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:aspect-square animate-fade'
              />
            </div>
          </div>
        </section>
      </main>
      <footer className='bg-muted py-4 px-6 shadow-md'>
        <div className='container mx-auto flex items-center justify-between'>
          <p className='text-foreground'>
            &copy; 2023 Closer. All rights reserved.
          </p>
          <nav>
            <ul className='flex space-x-4'>
              <li>
                <Link
                  href='#'
                  className='text-foreground hover:text-accent'
                  prefetch={false}>
                  Privacy
                </Link>
              </li>
              <li>
                <Link
                  href='#'
                  className='text-foreground hover:text-accent'
                  prefetch={false}>
                  Terms
                </Link>
              </li>
              <li>
                <Link
                  href='#'
                  className='text-foreground hover:text-accent'
                  prefetch={false}>
                  Support
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </footer>
    </div>
  );
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'>
      <path d='M20 6 9 17l-5-5' />
    </svg>
  );
}
